### ISSUE TITLE
可以看看源码吗？

### ISSUE THREAD

**Issue by tangka** [jmsht7355/jmsht7355.github.io#1]
本人纯前端，你那个统计浏览人数是怎么做的？看你也没有进行网络请求，怎么可以储存浏览次数的呢。谢谢

**Comment by jmsht7355** [comment]
我这边用的是hexo material-x主题的模板,统计这一块并不是我做的，我只是做了简单的样式删减，你可以去看一下原主题的源码仓库和配置主页
这是原主题模板的源码：https://github.com/xaoxuu/hexo-theme-material-x
下面是配置文档：https://xaoxuu.com/wiki/material-x/
如果你觉得麻烦的话可以看一下我这边做了精简的删减源码
博客源码：https://github.com/jmsht7355/fcx-blog

**Comment by tangka** [comment]
think you

**Comment by tangka** [comment]
think you

**Comment by jmsht7355** [comment]
不客气，共同学习！！！
